"""
Freeze current system_prompt.txt into a custom Ollama model.

Generates a Modelfile that extends a base model + bakes the system prompt
+ standard sampling params. Then runs `ollama create` to build it.

Usage:
    python freeze_persona.py <base_model> <new_model_name>

Examples:
    python freeze_persona.py dolphin-llama3:8b dolphin-agent-v1
    python freeze_persona.py huihui_ai/qwen2.5-coder-abliterate:7b verena-v1

After build, swap to the new model via:
    Discord:  !model <new_model_name>
    .env:     MODEL_NAME=<new_model_name>

Or check it's installed:
    ollama list | findstr <new_model_name>
"""
import sys, subprocess, os, re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROMPT_FILE = SCRIPT_DIR / "system_prompt.txt"


def main():
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    base = sys.argv[1].strip()
    new_name = sys.argv[2].strip().lower().replace(" ", "-")

    # Validate name (no shell injection risk + must be ollama-compatible)
    if not re.match(r"^[a-z0-9_\-:.]+$", new_name):
        print(f"ERROR: invalid model name {new_name!r} — use [a-z0-9_-:.]+", file=sys.stderr)
        sys.exit(1)

    if not PROMPT_FILE.exists():
        print(f"ERROR: {PROMPT_FILE} not found", file=sys.stderr)
        sys.exit(1)

    prompt_text = PROMPT_FILE.read_text(encoding="utf-8").strip()
    if not prompt_text:
        print(f"ERROR: {PROMPT_FILE} is empty — nothing to freeze", file=sys.stderr)
        sys.exit(1)

    # Modelfile SYSTEM uses triple-quoted strings. Escape any embedded triple-quotes.
    prompt_safe = prompt_text.replace('"""', '\\"\\"\\"')

    modelfile_content = (
        f"# Auto-generated by freeze_persona.py — do not edit by hand.\n"
        f"# Base: {base}\n"
        f"# Frozen from: {PROMPT_FILE}\n"
        f"# Prompt chars: {len(prompt_text)}\n"
        f"\n"
        f"FROM {base}\n"
        f"\n"
        f'SYSTEM """{prompt_safe}"""\n'
        f"\n"
        f"# Sampling params — tweak before ollama create if needed\n"
        f"PARAMETER temperature 0.8\n"
        f"PARAMETER top_p 0.9\n"
        f"PARAMETER num_ctx 4096\n"
        f"PARAMETER repeat_penalty 1.1\n"
        f"\n"
        f"# Stop strings — prevents the model from continuing past sentinel markers\n"
        f"PARAMETER stop \"[STOPPED\"\n"
        f"PARAMETER stop \"<|im_end|>\"\n"
    )

    modelfile_path = SCRIPT_DIR / f"Modelfile.{new_name}"
    modelfile_path.write_text(modelfile_content, encoding="utf-8")
    print(f"[1/2] Wrote Modelfile: {modelfile_path}")
    print(f"      Base: {base}")
    print(f"      Prompt baked: {len(prompt_text):,} chars")
    print()
    print(f"[2/2] Building model: ollama create {new_name} -f {modelfile_path.name}")
    print()

    result = subprocess.run(
        ["ollama", "create", new_name, "-f", str(modelfile_path)],
        capture_output=False,
    )
    if result.returncode != 0:
        print(f"\nERROR: ollama create failed (exit code {result.returncode})", file=sys.stderr)
        sys.exit(result.returncode)

    print()
    print(f"✅ DONE — `{new_name}` is now installed in ollama.")
    print()
    print(f"  Verify:        ollama list | findstr {new_name}")
    print(f"  Discord swap:  !model {new_name}")
    print(f"  .env default:  MODEL_NAME={new_name}")


if __name__ == "__main__":
    main()
